#include "micetitle.h"

QString MiceTitle::getTitle(int n)
{
    QString title = "Título desconhecido";

    if (this->contains(n))
    {
        title = this->value(n);
    }

    return title.append(" (/title ").append(QString::number(n)).append(")");
}

MiceTitle::MiceTitle()
{
    this->insert(0, "Little Mouse");
    this->insert(1, "Shaman Disciple");
    this->insert(2, "Accomplished Shaman");
    this->insert(3, "Shaman");
    this->insert(4, "Shaman Master");
    this->insert(5, "Greedy Mouse");
    this->insert(6, "Here ! Cheese !");
    this->insert(7, "Yeeeeah Cheese ^^");
    this->insert(8, "Cheeeeeese *-*");
    this->insert(9, "Fast Mouse");
    this->insert(10, "Agile Mouse");
    this->insert(11, "Pirate Mouse");
    this->insert(12, "Ninja Mouse");
    this->insert(13, "Inspired Shaman");
    this->insert(14, "Shaman Champion");
    this->insert(15, "Glorious Shaman");
    this->insert(16, "Shaman Duchess");
    this->insert(17, "Shaman Princess");
    this->insert(18, "Shaman Empress");
    this->insert(19, "Legendary Shaman");
    this->insert(20, "Immortal Shaman");
    this->insert(21, "The Chosen Shaman");
    this->insert(22, "Holy Shaman");
    this->insert(23, "Shaman Oracle");
    this->insert(24, "Shaman Prophet");
    this->insert(25, "Shamarvelous");
    this->insert(26, "Glutton Mouse");
    this->insert(27, "Gleany");
    this->insert(28, "Plumpy Mouse");
    this->insert(29, "Paunchy Mouse");
    this->insert(30, "Chubby Mouse");
    this->insert(31, "Fluffy Mouse");
    this->insert(32, "Tubby Mouse");
    this->insert(33, "The Chubby");
    this->insert(34, "The Puffy");
    this->insert(35, "Activist Mouse");
    this->insert(36, "Unionized Mouse");
    this->insert(37, "Mouse on Strike");
    this->insert(38, "The Cheese Initiated");
    this->insert(39, "The Cheese Adept");
    this->insert(40, "The Cheese Priest");
    this->insert(41, "The Reaper");
    this->insert(42, "Rogue Mouse");
    this->insert(43, "Looter");
    this->insert(44, "Stalker");
    this->insert(45, "Frothy Mouse");
    this->insert(46, "The Silent");
    this->insert(47, "Hawk Mouse");
    this->insert(48, "Cobra Mouse");
    this->insert(49, "Spidermouse");
    this->insert(50, "Quick Silver");
    this->insert(51, "Athletic Mouse");
    this->insert(52, "Hasty Mouse");
    this->insert(53, "Rocket Mouse");
    this->insert(54, "Sonic The Mouse");
    this->insert(55, "Pingless");
    this->insert(56, "Kamikaze");
    this->insert(57, "Warrior Mouse");
    this->insert(58, "Mach 1");
    this->insert(59, "Hunter");
    this->insert(60, "First!");
    this->insert(61, "Sniper");
    this->insert(62, "Flash");
    this->insert(63, "Supermouse");
    this->insert(64, "Light Speed");
    this->insert(65, "Time Traveler");
    this->insert(66, "Fast Wind");
    this->insert(67, "E=MouseC²");
    this->insert(68, "Jumper");
    this->insert(69, "The Untouchable");
    this->insert(70, "Wall-Jumper");
    this->insert(71, "LIGHTNING");
    this->insert(72, "Cheese Finder");
    this->insert(73, "Cheese Knight");
    this->insert(74, "Cheesegrubber");
    this->insert(75, "Fatty");
    this->insert(76, "Stout Mouse");
    this->insert(77, "Cheese Lover");
    this->insert(78, "Camembert");
    this->insert(79, "Pont-L'Évêque");
    this->insert(80, "Cheese Catcher");
    this->insert(81, "It's Over 9000");
    this->insert(82, "Collector");
    this->insert(83, "Cheeseleader");
    this->insert(84, "Cheese Thief");
    this->insert(85, "Cheese Creator");
    this->insert(86, "Cheese Pizza");
    this->insert(87, "Cheese Minister");
    this->insert(88, "Prodigy Mouse");
    this->insert(89, "Princess Of Transformice");
    this->insert(90, "Cheesoholic");
    this->insert(91, "The Cheesen One");
    this->insert(92, "Sailor Mouse");
    this->insert(93, "MAH CHEESE!");
    this->insert(94, "Ancient Shaman");
    this->insert(95, "Fearless Shaman");
    this->insert(96, "Almighty Shaman");
    this->insert(97, "Architect Shaman");
    this->insert(98, "Mademoiselle");
    this->insert(99, "Lady Chamane");
    this->insert(100, "Loved");
    this->insert(101, "Magician");
    this->insert(102, "Hero of Mice");
    this->insert(103, "Angel Shaman");
    this->insert(104, "The Creator");
    this->insert(105, "Absolute Shaman");
    this->insert(106, "Miraculous Shaman");
    this->insert(107, "Liberator");
    this->insert(108, "Troll Shaman");
    this->insert(109, "Ghost Shaman");
    this->insert(110, "Spirit");
    this->insert(111, "Demigodess Shaman");
    this->insert(112, "Last Hope");
    this->insert(113, "Redeemer");
    this->insert(114, "Goddess Shaman");
    this->insert(115, "Nice Mouse");
    this->insert(116, "Adorable Mouse");
    this->insert(117, "Charming Mouse");
    this->insert(118, "Pretty Mouse");
    this->insert(119, "Cute Mouse");
    this->insert(120, "Frivolous Mouse");
    this->insert(121, "Snob Mouse");
    this->insert(122, "Stylish Mouse");
    this->insert(123, "Actress Mouse");
    this->insert(124, "Fashion Mouse");
    this->insert(125, "Sexy");
    this->insert(126, "SuperStar");
    this->insert(127, "Little Snowflake");
    this->insert(128, "Christmas Spirit");
    this->insert(129, "Little Pixie");
    this->insert(130, "Santa Claus");
    this->insert(202, "The Wind Master");
    this->insert(210, "Alluring Mouse");
    this->insert(211, "Temptress");
    this->insert(212, "Latin Lover");
    this->insert(213, "Decorator");
    this->insert(214, "Builder");
    this->insert(215, "Manufacturer");
    this->insert(216, "Technician");
    this->insert(217, "Mechanic");
    this->insert(218, "Specialist");
    this->insert(219, "Inventor");
    this->insert(220, "Engineer");
    this->insert(221, "Inventive Mouse");
    this->insert(222, "Ingenious Mouse");
    this->insert(223, "Virtuoso");
    this->insert(224, "Sprinter");
    this->insert(225, "Batmouse");
    this->insert(226, "The Unseen");
    this->insert(227, "Unstoppable");
    this->insert(228, "¡Ándale! ¡Ándale!");
    this->insert(229, "Torpedo");
    this->insert(230, "Speedy Gorgonzola");
    this->insert(231, "Dynamite");
    this->insert(232, "Speedmaster");
    this->insert(233, "Whirlwind");
    this->insert(234, "Om Nom Nom");
    this->insert(235, "*-*");
    this->insert(236, "Cheese Addict");
    this->insert(237, "Cheesus");
    this->insert(238, "Queen of Cheese");
    this->insert(440, "Fromadmin");
    this->insert(444, "La Belette");
}
